In [16]:
import cv2
import tensorflow as tf
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img
import numpy as np

WIDTH = 128
HEIGHT = 128
DEPTH = 3
def prepare(filepath):
    #img_array=cv2.imread(filepath,cv2.IMREAD_GRAYSCALE)
    #new_array=cv2.resize(img_array,(HEIGHT,WIDTH))
    #arr = cv2.resize(new_array, (HEIGHT,WIDTH))
    #return arr.reshape(-1,HEIGHT,WIDTH,3)
    img = load_img(filepath)
    arr = img_to_array(img)
    arr = cv2.resize(arr, (HEIGHT,WIDTH))
    arr = np.array(arr, dtype="float")
    return arr.reshape(-1,HEIGHT,WIDTH,3)
    

model=tf.keras.models.load_model('C:/Users/AKANKSHA/Desktop/gen.hd5')
#img = cv2.imread('test.jpg')
def int_to_classes(i):
    if i >= 0 and i<1: return "No DR"
    elif i >= 1 and i<2: return "Mild"
    elif i >= 2 and i<3: return "Moderate"
    elif i >= 3 and i<4: return "Severe"
    elif i >= 4 and i<5: return "Proliferative DR"
    print("Invalid class ", i)
    return "Invalid Class"

In [17]:
from tkinter import *
import sys
import matplotlib as plt
from tkinter import ttk
import tkinter.filedialog
from tkinter.filedialog import askopenfilename # Open dialog box
from PIL import Image
import cv2, time
def open_File():   
    filename = askopenfilename(filetypes=[("images","*.jpeg")])
    prediction=model.predict([prepare(filename)])
    print(prediction)
    idx=np.argmax(prediction)
    #print(idx)
    b=Label(window,text=idx)
    b.place(x=170, y=190)
    c=int_to_classes(idx)
    a=Label(window,text=c)
    a.place(x=170, y=150)
window = Tk()                              # Create window
lbl=Label(window, text="Diabetic Retinopathy Detection System", fg='red', font=("Helvetica", 16))
lbl.place(x=60, y=50)
window.title("Check For Disease")               
l1=Label(window, text="Select image")
l1.grid(row=0,column=0)
l1.place(x=100, y=100)
btn1=Button(window,text="Browse image", width =14)
btn1.grid(row=0, column=3)
btn1.place(x=200, y=100)
window.geometry("500x300+10+10")
btn1.config(command=open_File)
window.mainloop()

[[1.000000e+00 0.000000e+00 9.692892e-30 0.000000e+00 0.000000e+00]]
[[1.0000000e+00 5.7755406e-37 2.3519930e-22 0.0000000e+00 0.0000000e+00]]
[[1.0000000e+00 0.0000000e+00 1.7227282e-26 0.0000000e+00 0.0000000e+00]]
